export {
  bearingDeg,
  compassLabel,
  homeRegionForLamp,
  regionAt,
  REGIONS,
  REGION_ORDER,
  type RegionDef,
  type RegionId,
} from "./regions";

export {
  districtAt,
  districtLabel,
  landUseAt,
  pickLampSocket,
  ACRE_LANES,
  DISTRICT,
  LAND_COLOR,
  LAMP_SOCKETS,
  LOTS,
  MAP_MASSES,
  STREET_HALF,
  WALK_HALF,
  WARD_EW,
  WARD_NS,
  type DistrictDef,
  type DistrictId,
  type LampSocket,
  type LandUse,
  type Lot,
  type PrefabId,
} from "./districts";

export {
  ABILITIES,
  ABILITY_ORDER,
  ARENA_RADIUS,
  CONDITIONS,
  DASH_STAMINA,
  HIGH_SCORE_LIMIT,
  INSPECT_RANGE,
  LAMPS,
  LAMP_ORDER,
  MAX_HP,
  MAX_STAMINA,
  NIGHT_MOTH_GAME_ID,
  SCORE_RETAIN,
  SIPHON_RANGE,
  SIP_RANGE,
  STARTER_ABILITIES,
  type AbilityDef,
  type AbilityId,
  type ConditionDef,
  type ConditionId,
  type LampAlignment,
  type LampDef,
  type LampKind,
} from "./catalog";

export {
  CAVES,
  POOLS,
  RETREAT,
  WATERWAYS,
  bakeHeightField,
  caveAt,
  computeHeightAt,
  distToWaterway,
  featureAt,
  heightAt,
  isWater,
  resetHeightField,
  maxFlyY,
  minFlyY,
  waterDepthAt,
  waterwayPoint,
  type CaveDef,
  type TerrainFeature,
  type Waterway,
} from "./terrain";

export {
  buildingColliders,
  colliderForLot,
  lampCollider,
  indexColliders,
  nearbyColliders,
  resolveSphere,
  supportY,
  type Collider,
  type ColliderIndex,
  type ColliderKind,
  type HitResult,
} from "./collision";

export {
  BEETLE,
  BLOOMS,
  BLOOM_SITES,
  BOSSES,
  DRAGONFLY,
  MITES,
  MITE_ORDER,
  POLLINATE_RANGE,
  SPIDER,
  WEB_RADIUS,
  WEB_SITES,
  WEB_TRIGGER_Y,
  beetleScore,
  canEscapeBoss,
  composeFauna,
  infestationCount,
  miteForNight,
  miteScore,
  spiderScore,
  type BloomDef,
  type BloomSite,
  type BossId,
  type FaunaMix,
  type FoeId,
  type FriendId,
  type MiteDef,
  type MiteHue,
  type WebSite,
} from "./fauna";

export {
  auroraScoreMul,
  composeEvents,
  eventDuration,
  eventLine,
  eventTitle,
  isBossEvent,
  type EventPlan,
  type NightEventKind,
} from "./events";

export {
  SHOT_TAGS,
  parseShotBody,
  shotFilename,
  slugRegion,
  type ShotPayload,
} from "./shot";

export {
  abilityDamage,
  applyCombo,
  clamp01,
  clampInt,
  comboMultiplier,
  composeNight,
  contactDamage,
  isLure,
  isTrueLamp,
  lampHp,
  lampSipScore,
  lureKillScore,
  nextAbility,
  nextUnlock,
  nightClearScore,
  nightLampCount,
  nightSparkCount,
  sipOutcome,
  scatterRegionId,
  sparkKillScore,
  tutorialLamps,
  unlockedAbilities,
  BONUS_NECTAR,
  BONUS_SCORE,
  BONUS_XP,
  xpForLamp,
  xpForLureKill,
  type NightMix,
  type SipOutcome,
} from "./rules";
