export {
  bearingDeg,
  compassLabel,
  homeRegionForLamp,
  regionAt,
  REGIONS,
  REGION_ORDER,
  type RegionDef,
  type RegionId,
} from "./regions";

export {
  ABILITIES,
  ABILITY_ORDER,
  ARENA_RADIUS,
  CONDITIONS,
  DASH_STAMINA,
  HIGH_SCORE_LIMIT,
  INSPECT_RANGE,
  LAMPS,
  LAMP_ORDER,
  MAX_HP,
  MAX_STAMINA,
  NIGHT_MOTH_GAME_ID,
  SCORE_RETAIN,
  SIPHON_RANGE,
  SIP_RANGE,
  STARTER_ABILITIES,
  type AbilityDef,
  type AbilityId,
  type ConditionDef,
  type ConditionId,
  type LampAlignment,
  type LampDef,
  type LampKind,
} from "./catalog";

export {
  abilityDamage,
  applyCombo,
  clamp01,
  clampInt,
  comboMultiplier,
  composeNight,
  contactDamage,
  isLure,
  isTrueLamp,
  lampHp,
  lampSipScore,
  lureKillScore,
  nextAbility,
  nextUnlock,
  nightClearScore,
  nightLampCount,
  nightSparkCount,
  sipOutcome,
  scatterRegionId,
  sparkKillScore,
  tutorialLamps,
  unlockedAbilities,
  BONUS_NECTAR,
  BONUS_SCORE,
  BONUS_XP,
  xpForLamp,
  xpForLureKill,
  type NightMix,
  type SipOutcome,
} from "./rules";
